version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_cultivo
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "Cultivo"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3307:3306"
    volumes:
      - C:/Consultas/mysql_data:/var/lib/mysql
      - C:/Consultas/init.sql:/docker-entrypoint-initdb.d/init.sql
